services:
  db:
    image: mysql:8.0
    container_name: ems-db
    environment:
      MYSQL_ROOT_PASSWORD: 9100479404
      MYSQL_DATABASE: EmployeeManagementSystem
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p9100479404"]
      interval: 5s
      timeout: 3s
      retries: 20
    # ports:
    #   - "3307:3306"

  backend:
    build:
      context: ./BE/EmployeeManagementSystem
      dockerfile: dockerfile.one
    container_name: ems-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/EmployeeManagementSystem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 9100479404
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./FE/ems
      dockerfile: dockerfile.one
    container_name: ems-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  mysql_data: {}
